# Generated by Django 5.1.3 on 2025-01-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_documents_remove_project_plans_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuilderDetails',
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
    ]
