# Generated by Django 5.1.3 on 2025-01-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_delete_builderdetails_delete_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='availability',
            field=models.BooleanField(default=False),
        ),
    ]
