# Generated by Django 5.1.3 on 2025-01-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_created_at_project_updated_at_inquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_type',
            field=models.CharField(blank=True, choices=[('specific_property', 'Specific Property'), ('general', 'General Inquiry')], max_length=20, null=True),
        ),
    ]
