# Generated by Django 5.1.3 on 2025-01-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_availability_alter_project_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bathrooms',
            field=models.FloatField(),
        ),
    ]
