# Generated by Django 5.1.3 on 2025-02-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_project_bathrooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='avialable_date',
            new_name='available_date',
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
