# Generated by Django 5.1.3 on 2025-02-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_rename_avialable_date_project_available_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
