# Generated by Django 5.0.4 on 2025-02-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_project_thumbnail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='lease_term',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='move_in_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
