# Generated by Django 5.1.3 on 2025-03-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_rename_postal_code_project_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('General Questions', 'General Questions'), ('Property Owners/Landlords', 'Property Owners/Landlords'), ('For Tenants', 'For Tenants')], default='General Questions', max_length=100),
        ),
    ]
