# Generated by Django 5.1.3 on 2025-03-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_faq_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('General Questions', 'General Questions'), ('Property Owners/Landlords', 'Property Owners/Landlords'), ('Tenants', 'Tenants')], default='General Questions', max_length=100),
        ),
    ]
