# Generated by Django 5.1.3 on 2025-03-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_faq_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
