# Generated by Django 5.1.3 on 2025-01-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
