# Generated by Django 5.1.3 on 2025-01-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_ourteam_created_at_ourteam_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
