# Generated by Django 5.1.3 on 2025-01-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_author_category_remove_tag_name_tag_tag_name_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meta_title',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=300),
        ),
    ]
