# Generated by Django 5.1.3 on 2025-01-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
