# Generated by Django 5.1.3 on 2025-01-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_meta_description_alter_post_meta_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(max_length=500),
        ),
    ]
